import { FilterCategory } from '../models/catalog-filter.model';

export const FILTER_CATEGORIES_UK: FilterCategory[] = [
  {
    title: 'Локація',
    key: 'location',
    description: 'Обери місто',
    options: [
      {
        id: 35,
        key: 'kyiv',
        label: 'Київ',
        description: 'Заклади Києва',
        imageURL: './assets/filter/kyiv.jpg',
      },
      {
        id: 0,
        key: 'lviv',
        label: 'Львів',
        description: 'Заклади Львова',
        imageURL: './assets/filter/lviv.jpg',
      },
    ],
  },
  {
    title: 'Мета візиту',
    key: 'purpose',
    description: 'Навіщо ти тут?',
    options: [
      {
        id: 3,
        key: 'workFriendly',
        label: 'Зручно для роботи',
        description: 'Тихо, спокійно, є Wi-Fi',
        imageURL: './assets/filter/workFriendly.jpg',
        iconURL: './assets/icons/workFriendly.svg',
        iconURLDarkThema: './assets/icons/workFriendlyDarkThema.svg',
      },
      {
        id: 48,
        key: 'grabAndGo',
        label: 'На виніс',
        description: 'Швидка зупинка, takeout',
        imageURL: './assets/filter/grabAndGo.jpg',
        iconURL: './assets/icons/grabAndGo.svg',
        iconURLDarkThema: './assets/icons/grabAndGoDarkThema.svg',
      },
      {
        id: 49,
        key: 'brunch',
        label: 'Сніданок-бранч',
        description: 'Ранкові страви та снеки',
        imageURL: './assets/filter/brunch.jpg',
        iconURL: './assets/icons/brunch.svg',
        iconURLDarkThema: './assets/icons/brunchDarkThema.svg',
      },
      {
        id: 52,
        key: 'chill',
        label: 'Розслабитись та відпочити',
        description: 'Повільний темп, затишна атмосфера',
        imageURL: './assets/filter/chill.jpg',
        iconURL: './assets/icons/chill.svg',
        iconURLDarkThema: './assets/icons/chillDarkThema.svg',
      },
      {
        id: 55,
        key: 'date',
        label: 'Датування чи затишний час',
        description: 'Романтика, інтимна атмосфера',
        imageURL: './assets/filter/date.jpg',
        iconURL: './assets/icons/date.svg',
        iconURLDarkThema: './assets/icons/dateDarkThema.svg',
      },
    ],
  },
  {
    title: 'Зручності',
    key: 'amenities',
    description: 'Додатковий комфорт',
    options: [
      {
        id: 47,
        key: 'freeWifi',
        label: 'Wi-Fi',
        description: 'Швидкий та стабільний інтернет',
        imageURL: './assets/filter/freeWifi.jpg',
        iconURL: './assets/icons/freeWifi.svg',
        iconURLDarkThema: './assets/icons/freeWifiDarkThema.svg',
      },
      {
        id: 8,
        key: 'petFriendly',
        label: 'Дружнє до тварин',
        description: 'Тварини ласкаво просимо',
        imageURL: './assets/filter/petFriendly.jpg',
        iconURL: './assets/icons/petFriendly.svg',
        iconURLDarkThema: './assets/icons/petFriendlyDarkThema.svg',
      },
      {
        id: 7,
        key: 'veganOptions',
        label: 'Веганські опції',
        description: 'Рослинна їжа та напої',
        imageURL: './assets/filter/veganOptions.jpg',
        iconURL: './assets/icons/veganOptions.svg',
        iconURLDarkThema: './assets/icons/veganOptionsDarkThema.svg',
      },
      {
        id: 54,
        key: 'quietZone',
        label: 'Тиха зона',
        description: 'Мінімум шуму, максимум фокусу',
        imageURL: './assets/filter/quietZone.jpg',
        iconURL: './assets/icons/quietZone.svg',
        iconURLDarkThema: './assets/icons/quietZoneDarkThema.svg',
      },
      {
        id: 50,
        key: 'outdoorSeating',
        label: 'Місця на відкритому повітрі',
        description: 'Тераси або столики надворі',
        imageURL: './assets/filter/outdoorSeating.jpg',
        iconURL: './assets/icons/outdoorSeating.svg',
        iconURLDarkThema: './assets/icons/outdoorSeatingDarkThema.svg',
      },
    ],
  },
  {
    title: 'Атмосфера та стиль',
    key: 'vibe',
    description: 'Яке враження?',
    options: [
      {
        id: 10,
        key: 'minimalist',
        label: 'Мінімалістичний',
        description: 'Чистий, просторий інтер’єр',
        imageURL: './assets/filter/minimalist.jpg',
        iconURL: './assets/icons/minimalist.svg',
        iconURLDarkThema: './assets/icons/minimalistDarkThema.svg',
      },
      {
        id: 51,
        key: 'vintageRetro',
        label: 'Вінтаж / ретро',
        description: 'Старовинні меблі та настрій',
        imageURL: './assets/filter/vintageRetro.jpg',
        iconURL: './assets/icons/vintageRetro.svg',
        iconURLDarkThema: './assets/icons/vintageRetroDarkThema.svg',
      },
      {
        id: 58,
        key: 'livelySocial',
        label: 'Жива та соціальна',
        description: 'Багато людей, енергія, музика',
        imageURL: './assets/filter/livelySocial.jpg',
        iconURL: './assets/icons/livelySocial.svg',
        iconURLDarkThema: './assets/icons/livelySocialDarkThema.svg',
      },
      {
        id: 53,
        key: 'greenNatural',
        label: 'Зелений та натуральний',
        description: 'Рослини, дерево, еко-атмосфера',
        imageURL: './assets/filter/greenNatural.jpg',
        iconURL: './assets/icons/greenNatural.svg',
        iconURLDarkThema: './assets/icons/greenNaturalDarkThema.svg',
      },
      {
        id: 56,
        key: 'darkMoody',
        label: 'Темно та атмосферно',
        description: 'Приглушене світло, глибокі тони',
        imageURL: './assets/filter/darkMoody.jpg',
        iconURL: './assets/icons/darkMoody.svg',
        iconURLDarkThema: './assets/icons/darkMoodyDarkThema.svg',
      },
    ],
  },
];
